// lib/types.ts
//
// Shared domain types for the v4 Next.js port. Mirrors the v3 CONTRACT and
// the data shapes generated by server/data-generator.ts. These types are
// consumed by both server code and the API client / hooks layer.
//
// All types are exported as named interfaces / unions so the smoke script,
// the route handlers, and the UI share the same vocabulary.

// ----- enums / unions -----------------------------------------------------

export type Direction = 'Dong' | 'Nan' | 'Xi' | 'Bei';

export type EquipmentType =
  | '一级配电箱'
  | '二级配电箱'
  | 'OTN'
  | '光交';

export type EquipmentStatus = 'online' | 'offline';

export type RoomType = 'main' | 'aux' | 'riser';

export type CableIo = 'in' | 'out';

// ----- value types --------------------------------------------------------

// One vertex in a building footprint polygon (local 2D metres inside the
// floor slab). The polygon is auto-closed by THREE.ExtrudeGeometry so we
// don't repeat the first vertex at the end.
export type FootprintVertex = [number, number];

// Local 2D position of an Equipment item on a floor. Both x and y are in
// [0, 1] — see the v3 contract.
export interface EquipmentPosition {
  x: number;
  y: number;
}

// ----- entities -----------------------------------------------------------

export interface Cable {
  id: string;
  name: string;
  direction: Direction;
  io: CableIo;
  peer: string;
  type: string;
  cores: number;
}

export interface Floor {
  floorNo: number;
  label: string;
  cables: Cable[];
}

export interface Room {
  id: string;
  buildingId: string;
  name: string;
  floorNo: number;
  type: RoomType;
}

export interface Equipment {
  id: string;
  buildingId: string;
  type: EquipmentType;
  floorNo: number;
  roomId: string;
  status: EquipmentStatus;
  position: EquipmentPosition;
}

// The full Building shape that the detail endpoint returns. The list
// endpoint returns a BuildingListEntry instead (lighter payload).
export interface Building {
  id: string;
  name: string;
  lng: number;
  lat: number;
  address: string;
  floorCount: number;
  floors: Floor[];
  rooms: Room[];
  equipment: Equipment[];
  // Hand-curated polygon for non-rectangular slabs, or null for the default
  // rectangular slab. Polygon vertices are local 2D metres inside the slab
  // (SLAB_W/2 = SLAB_D/2 = 2.0).
  footprint: FootprintVertex[] | null;
  // Unique EquipmentType values derived from `equipment`. Used by the map
  // filter panel for the OR-semantic marker toggle.
  equipmentTypes: EquipmentType[];
  // Convenience aggregate — sum of cables across all floors. Present on
  // both list and detail so the map popup doesn't need a second request.
  cableCount: number;
}

// Lighter payload returned by GET /api/buildings. Skips the heavy floors /
// rooms / equipment arrays so the map view loads fast.
export interface BuildingListEntry {
  id: string;
  name: string;
  lng: number;
  lat: number;
  address: string;
  floorCount: number;
  cableCount: number;
  equipmentTypes: EquipmentType[];
}

// ----- runtime helpers ----------------------------------------------------

export const VALID_DIRECTIONS: ReadonlySet<Direction> = new Set([
  'Dong',
  'Nan',
  'Xi',
  'Bei',
]);

export const VALID_EQUIPMENT_TYPES: ReadonlySet<EquipmentType> = new Set([
  '一级配电箱',
  '二级配电箱',
  'OTN',
  '光交',
]);

export const VALID_EQUIPMENT_STATUS: ReadonlySet<EquipmentStatus> = new Set([
  'online',
  'offline',
]);
